# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/taller_nbdev',
                'doc_host': 'https://PaulinaPC6.github.io',
                'git_url': 'https://github.com/PaulinaPC6/taller_nbdev',
                'lib_path': 'taller_nbdev'},
  'syms': {'taller_nbdev.core': {'taller_nbdev.core.foo': ('core.html#foo', 'taller_nbdev/core.py')}}}
